import { PROJECTS, type ProjectItem } from "@/lib/data/projects";

export interface ProjectArticleSection {
  title: string;
  paragraphs: string[];
  codeSnippet?: string;
  codeLanguage?: string;
}

export type RegisteredProject = ProjectItem & {
  articleSections?: ProjectArticleSection[];
};

export const ADDITIONAL_PROJECTS: RegisteredProject[] = [
  {
    slug: "mlbb-post-game-extractor",
    title: "MLBB Post-Game Extractor",
    tagline:
      "Client-side MLBB screenshot extractor built around configurable crop presets, Tesseract.js OCR, and long or role-positioned CSV exports.",
    category: "web",
    categoryLabel: "Web & Tools",
    tier: "focused",
    role: "Creator & Developer",
    timeline: "2026",
    featured: false,
    order: 13,
    glowColor: "cyan",
    brandColor: "#22D3EE",
    icon: "scan-text",
    platforms: [{ name: "Web", icon: "web" }],
    stack: [
      { name: "React 18", icon: "react" },
      { name: "Vite", icon: "vite" },
      { name: "Tesseract.js", icon: "ocr" },
      { name: "HTML5 Canvas", icon: "canvas" },
      { name: "WebAssembly", icon: "wasm" },
      { name: "Web Workers", icon: "worker" },
      { name: "localStorage", icon: "storage" },
      { name: "Vitest", icon: "test" },
    ],
    githubUrl: "https://github.com/Aedwon/mlbb-post-game-extractor",
    summary:
      "Browser tool that maps post-game screenshots to five tab presets, slices stat columns into ten player records, checks battle IDs across a batch, and exports match data as a 40-column long CSV or a 226-column wide CSV.",
    problem:
      "The extractor turns MLBB post-game screenshots into structured ten-player match data using configurable crop presets and browser-based OCR.",
    architecture: [],
    results:
      "The current implementation covers batch screenshot mapping, Battle ID verification, editable player review, match metadata, and selectable long or role-positioned CSV exports without a backend.",
    articleSections: [
      {
        title: "Building the batch around crop presets",
        paragraphs: [
          "The extractor works from the five MLBB post-game tabs it knows about: Main, DPS, Team, Overall, and Farm. Each uploaded screenshot gets a preset, and the app blocks OCR when two screenshots are assigned to the same tab. The batch architecture landed early in the repository history along with the switch from reading one image to building ten player records across several screenshots.",
          "Each preset is a collection of crop boxes in source-image coordinates. The screenshot is drawn to a full-resolution canvas while the browser displays a scaled version, so dragging a box in the UI still updates coordinates against the original image. Those boxes are saved in `localStorage` using the image dimensions and preset name as the key. A calibrated Main preset at one resolution does not overwrite the configuration for another resolution or another tab.",
          "Most boxes represent a full stat column instead of one player cell. During OCR, the code divides a column's height into five equal slices, adds a small amount of padding around each crop, and sends the slices through Tesseract one at a time. Crops on the left half become players 1 through 5. Crops on the right become players 6 through 10. Header fields such as Battle ID and duration use a single crop instead.",
          "Before extracting the stat columns, the app makes a separate Battle ID pass over the uploaded screenshots. It strips the OCR result down to digits and compares each usable ID with the first one using Levenshtein distance. A distance above three stops the batch. It is a small check, but it keeps screenshots from different matches from being merged into the same ten-player record.",
        ],
      },
      {
        title: "The red side needed its own field order",
        paragraphs: [
          "The crop editor has a symmetry lock because the two team layouts share much of the same geometry. Default red-side boxes are generated by moving the blue group to the other half of the screenshot while preserving the spacing inside the group. Moving or resizing one side can update its paired box on the other side as well.",
          "The field order is not fully symmetric, though. The current defaults have explicit red-side orders for the Main and DPS tabs. This distinction came from a concrete bug in the DPS export. The red-side crops were landing on valid cells, but Hero Damage and Consecutive Kills were being attached to the wrong fields because the code assumed the blue-side column sequence also described the red side.",
          "The fix was one line in `RED_COLUMN_ORDER`, adding the DPS sequence as `consec_kills` followed by `hero_dmg`. That kept the mirroring code for positioning while giving tabs with different semantics their own field order. It is also why I would not replace the crop presets with a single blanket rule for both halves of the scoreboard.",
        ],
      },
      {
        title: "Exporting a match instead of dumping OCR text",
        paragraphs: [
          "The match schema was added in a sequence of small commits on May 2. The repository first added a duration parser and roster validation, then the role and hero constants. The long serializer came next, followed by the role-positioned wide serializer. After that, the duration crop, DPS mapping fix, player review fields, match metadata form, and final export picker were wired into the application.",
          "The review step groups OCR values by player and keeps the extracted stat fields editable. Each player also needs a hero and one of the five roles. Confirmation stays disabled while a hero or role is missing, or when the same role appears twice on one side. That validation also protects the wide export because the serializer finds each slot by its side and role. Without unique role assignments, a column such as `blue_mid_kills` would not have one unambiguous player to read from.",
          "The long CSV keeps one row per player. It has 16 match-level columns, five player metadata columns, and 19 stat columns for a total of 40. Match information such as Battle ID, patch, duration, winner, ban mode, and bans is repeated across the ten player rows.",
          "The wide CSV turns the same match into one 226-column row. It starts with the same 16 match columns, then writes ten fixed role slots in Blue then Red order. Within each side the order is EXP, Jungle, Mid, Roam, and Gold. Each slot contains IGN and hero followed by the 19 stat fields. The serializer therefore does the reshaping itself instead of requiring a separate pivot after export.",
          "Patch, winning side, and bans are manual metadata fields in the current UI. Duration comes from OCR and is converted from `MM:SS` to seconds only when it matches that format. The crop configurations and IGN history persist in `localStorage`, while the current match metadata and player assignments are reset after a match is saved. Screenshot processing and CSV generation stay in the browser. There is no backend in the current application path.",
        ],
      },
    ],
  },
  {
    slug: "webp-unli",
    title: "WebP Unli",
    tagline:
      "Static browser image converter built around libvips through WebAssembly, with batch conversion, per-file settings, and no image upload step.",
    category: "web",
    categoryLabel: "Web & Tools",
    tier: "focused",
    role: "Creator & Developer",
    timeline: "2026",
    featured: false,
    order: 14,
    glowColor: "green",
    brandColor: "#22C55E",
    icon: "image-down",
    platforms: [{ name: "Web", icon: "web" }],
    stack: [
      { name: "Next.js 16", icon: "nextjs" },
      { name: "TypeScript", icon: "typescript" },
      { name: "Tailwind CSS", icon: "tailwind" },
      { name: "wasm-vips", icon: "wasm" },
      { name: "WebAssembly", icon: "wasm" },
      { name: "Web Workers", icon: "worker" },
      { name: "fflate", icon: "zip" },
      { name: "Vitest", icon: "test" },
      { name: "Playwright", icon: "test" },
    ],
    githubUrl: "https://github.com/Aedwon/webp-unli",
    summary:
      "Static browser image converter that runs libvips in a Web Worker, supports per-file batch settings, and keeps source images on the user's device.",
    problem:
      "WebP Unli is a browser converter that keeps source images on the user's device. The site is a static Next.js export, with image conversion handled locally through wasm-vips.",
    architecture: [],
    results:
      "The current tool covers local file selection through WebP download, including batch conversion, per-file settings, reconversion, and ZIP downloads.",
    articleSections: [
      {
        title: "Local conversion with libvips",
        paragraphs: [
          "WebP Unli is a browser converter that keeps source images on the user's device. The site is a static Next.js export. Image decoding, resizing, WebP encoding, and metadata stripping all happen locally through `wasm-vips`, so there is no image-processing API or upload queue behind the page.",
          "Each file's `ArrayBuffer` is transferred to a module worker. libvips decodes it, applies the selected resize and WebP options, then transfers the encoded buffer back. The first load includes roughly 10 MB of WebAssembly runtime files, which the browser can cache afterward.",
        ],
      },
      {
        title: "The batch queue changed after the first implementation",
        paragraphs: [
          "The first conversion flow could already process multiple files. A later commit fixed state around reconversion and overlapping jobs. `runConversion` originally closed over the `files` array. It now reads the current queue through a ref, keeps a count of active conversion batches, and copies the nested resize settings when a file enters the queue.",
          "Each file keeps its own settings after that point. Completed files can be converted again with different options, and two or more finished images can be packaged into one ZIP with `fflate`.",
        ],
      },
      {
        title: "Production loading needed two fixes",
        paragraphs: [
          "The worker originally lived beside the application code as TypeScript. Turbopack emitted it as a raw `.ts` asset in production, so the browser could not execute it and the loading screen never received its ready message. I moved the worker to `public/worker.js` and load it directly as a module worker.",
          "That fixed the worker file, but `wasm-vips` could still hang during initialization. Its `SharedArrayBuffer` and pthread path requires a cross-origin isolated page. Local development gets the COOP and COEP headers from `next.config.js`. The Vercel deployment sets the same headers in `vercel.json` because those Next.js headers are not carried into the static export.",
        ],
      },
      {
        title: "Where it is now",
        paragraphs: [
          "The input layer recognizes JPG, PNG, GIF, WebP, AVIF, TIFF, BMP, SVG, HEIC, and HEIF through MIME types with an extension fallback. Animated GIFs are flagged because the current converter only keeps the first frame. HEIC and HEIF files are accepted for conversion, while the file card skips a browser preview when the format cannot be displayed natively.",
          "Playwright covers the basic PNG and JPG conversion paths, multi-file download, removing files from the queue, and the conversion controls. The current conversion and export path runs without a backend.",
        ],
      },
    ],
  },
  {
    slug: "lakambini-events-redesign",
    title: "Lakambini Events Redesign",
    tagline:
      "Redesign of Lakambini Events across five core pages and nine service pages, with a shared content model and custom layouts for each division.",
    category: "web",
    categoryLabel: "Web & Tools",
    tier: "focused",
    role: "Redesign & Frontend Developer",
    timeline: "2026",
    featured: false,
    order: 15,
    glowColor: "green",
    brandColor: "#E9C255",
    icon: "layout-template",
    platforms: [{ name: "Web", icon: "web" }],
    stack: [
      { name: "Next.js", icon: "nextjs" },
      { name: "TypeScript", icon: "typescript" },
      { name: "Tailwind CSS v4", icon: "tailwind" },
      { name: "Framer Motion", icon: "motion" },
      { name: "next/image", icon: "nextjs" },
      { name: "next/font", icon: "nextjs" },
    ],
    githubUrl: "https://github.com/Aedwon/lakambini-redesign",
    summary:
      "Lakambini Events redesign with nine dedicated service pages, shared division data, and a frontend that grew most around the navigation and accessibility work.",
    problem:
      "Lakambini has nine service divisions covering live entertainment, multimedia, event production, training, design, community work, software, and spatial builds. I gave each division its own static page instead of stretching one Services template across all of them. The repeated names, capabilities, hero copy, and cross-links live in a shared TypeScript file, so the page layouts can differ without copying the same content everywhere.",
    architecture: [
      {
        title: "Nine divisions, nine pages",
        description:
          "The division routes are static. TANGHAL, DALOY, TAYO, and the other services can each use their own deep-dive sections, while the shared data file handles the content that repeats between pages. The visual rules work the same way. Noto Serif, Manrope, the emerald surface colors, and the main spacing decisions live in Tailwind v4 theme tokens and reusable utilities. There are fourteen pages in the current build, so keeping those values in one place saves me from fixing the same small inconsistency several times.",
      },
      {
        title: "The header got complicated",
        description:
          "What looks like a normal header ended up needing separate state for the desktop services menu, the mobile menu, the mobile services accordion, scroll progress, route changes, focus return, and reduced motion. The Git history shows the layout shell first, scroll-based styling after that, then a later move to requestAnimationFrame interpolation over the first 80 pixels. The accessibility pass came later and added the keyboard and menu behavior that was missing from the earlier implementation. Mobile controls were also brought to a 44 pixel touch baseline during that pass.",
      },
    ],
    results:
      "The page structure is in place across five core pages and nine service pages. The remaining work is mostly photography. Many of the larger slots still point to stock or reference images, and the repository only contains the real Lakambini logo locally. I wrote an archive image brief that lists the real event photo each slot needs, including the crop, subject, mood, and past projects worth checking. I am leaving those placeholders alone until the actual archive can replace them.",
  },
];

export const ALL_PROJECTS: RegisteredProject[] = [
  ...PROJECTS,
  ...ADDITIONAL_PROJECTS,
].sort((a, b) => a.order - b.order);
